In [1]:
import numpy as np

# Set the random seed using the last two digits of your roll number
np.random.seed(23)  # Change this number to your last two digits

# Generate a 5x5 matrix with random integers between 0 and 9
A = np.random.randint(0, 10, (5, 5))

print("Original matrix A:")
print(A)

# Reduce A to its Row Echelon Form
rows, cols = A.shape
current_row = 0
for col in range(cols):
    # Find the first non-zero entry in the current column
    nonzero_row = current_row
    while nonzero_row < rows and A[nonzero_row, col] == 0:
        nonzero_row += 1
    
    # If found, swap the current row with the row containing the non-zero entry
    if nonzero_row < rows:
        A[[current_row, nonzero_row]] = A[[nonzero_row, current_row]]
        
        # Make the leading entry of the current column 1
        A[current_row] = A[current_row] / A[current_row, col]
        
        # Eliminate the entries below the leading entry
        for i in range(current_row + 1, rows):
            A[i] = A[i] - A[current_row] * A[i, col]
        
        current_row += 1

print("\nRow Echelon Form of matrix A:")
print(A)


Original matrix A:
[[3 6 8 9 6]
 [8 7 9 3 6]
 [1 2 5 5 0]
 [5 0 9 9 3]
 [1 7 4 1 1]]

Row Echelon Form of matrix A:
[[1 2 2 3 2]
 [0 1 0 2 1]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
